// Copy for the public-sector services page, one entry per language.
// build.mjs renders each into its own static page. Text between
// *asterisks* is set in the serif italic.
export const LANGS = {
  es: { dir: '', htmlLang: 'es', hreflang: 'es', locale: 'es_ES', label: 'ES', name: 'Castellano' },
  va: { dir: 'va/', htmlLang: 'ca-valencia', hreflang: 'ca', locale: 'ca_ES', label: 'VA', name: 'Valencià' },
  en: { dir: 'en/', htmlLang: 'en', hreflang: 'en', locale: 'en_GB', label: 'EN', name: 'English' },
};

export const STRINGS = {
  es: {
    title: 'Accesibilidad web e IA para ayuntamientos — Victor Esteban',
    description: 'Accesibilidad web, actas de pleno con IA y asistentes con los documentos del propio ayuntamiento. Pilotos acotados con precio cerrado, datos en la UE y siempre con validación de secretaría.',
    skip: 'Saltar al contenido',
    brandLabel: 'Victor Esteban, ver trayectoria completa',
    headerRole: 'Servicios para administraciones públicas',
    sectionsLabel: 'Secciones',
    languageLabel: 'Idioma',
    navServices: 'Servicios',
    navHow: 'Cómo trabajo',
    navDemo: 'Pedir demo',
    introLabel: 'Introducción',
    eyebrow: 'Para ayuntamientos y otras administraciones públicas',
    headline: 'Accesibilidad web e *IA práctica* para ayuntamientos.',
    lede: 'Os ayudo a cumplir la normativa de accesibilidad y a ahorrar horas de secretaría con IA: actas de pleno, respuestas a partir de vuestros propios documentos y anonimización para el portal de transparencia. Pilotos pequeños, con precio cerrado, y siempre con una persona de vuestro equipo validando el resultado.',
    ctaDemo: 'Pide una demo de 15 minutos',
    ctaServices: 'Ver los servicios ↓',
    sheetTitle: 'Ficha del servicio',
    stamp: 'Contrato menor',
    sheet: [
      ['Contratación', 'Contrato menor, con precio cerrado antes de empezar'],
      ['Formato', 'Piloto acotado con vuestros documentos reales'],
      ['Revisión', 'Siempre vuestra. Nada se publica sin validar'],
      ['Datos', 'Tratados en la UE, con contrato de encargo (RGPD)'],
      ['Idiomas', 'Castellano y valenciano'],
    ],
    servicesEyebrow: 'Servicios',
    servicesTitle: 'Tres problemas concretos, *resueltos* con pilotos pequeños.',
    deliverables: 'Qué recibís',
    services: [
      {
        tile: 'flor',
        tag: 'Diagnóstico · corrección · mantenimiento',
        name: 'Accesibilidad web',
        audience: 'Web municipal y sede electrónica',
        problem: 'El Real Decreto 1112/2018 obliga a que la web y la sede electrónica sean accesibles y a publicar una declaración de accesibilidad actualizada. Muchas no pasan una revisión básica: contraste, formularios, navegación con teclado o PDF sin etiquetar.',
        items: [
          'Diagnóstico según la norma UNE-EN 301 549 (WCAG 2.1 AA), con cada problema priorizado.',
          'Corrección de las incidencias, o instrucciones concretas para vuestro proveedor.',
          'Declaración de accesibilidad redactada y lista para publicar.',
          'Mantenimiento anual opcional: revisiones periódicas y apoyo con las reclamaciones.',
        ],
      },
      {
        tile: 'estrella',
        tag: 'Piloto de 3 meses',
        name: 'Actas de pleno con IA',
        audience: 'Secretaría',
        problem: 'Redactar el acta de un pleno a partir de la grabación lleva horas de secretaría: escuchar, transcribir, resumir cada intervención y recoger los acuerdos y las votaciones.',
        items: [
          'Transcripción de la grabación, en castellano o en valenciano, con cada intervención identificada.',
          'Borrador del acta con el formato de vuestro ayuntamiento: asistencia, orden del día, intervenciones, acuerdos y votaciones.',
          'La secretaría revisa, corrige y firma. La herramienta solo prepara el borrador.',
        ],
      },
      {
        tile: 'rombe',
        tag: 'Piloto acotado',
        name: 'Asistente con vuestros documentos',
        audience: 'Secretaría o atención ciudadana',
        problem: 'Las mismas preguntas llegan una y otra vez a secretaría o a atención ciudadana, y la respuesta está en una ordenanza, un procedimiento o una resolución que hay que buscar.',
        items: [
          'Un asistente para el personal o para la ciudadanía que responde a partir de vuestras ordenanzas, procedimientos y trámites.',
          'Cada respuesta cita el documento del que sale, para poder comprobarla.',
          'Avisa de que es una IA, como exige el Reglamento Europeo de IA.',
          'El piloto se centra en un área o un tipo de consulta.',
        ],
        variant: {
          label: 'Variante pequeña',
          name: 'Anonimización de documentos.',
          text: 'Resoluciones, contratos o actas listos para el portal de transparencia, con los datos personales ocultos y una lista de lo ocultado para revisarla antes de publicar.',
        },
      },
    ],
    workshopKicker: 'Para empezar',
    workshopTitle: 'Taller de IA para secretaría e intervención',
    workshopText: 'Una sesión práctica con vuestro equipo: qué puede hacer hoy la IA con documentos municipales, qué no conviene hacer con ella y cómo usarla sin exponer datos personales. Sin compromiso de contratar nada más.',
    workshopMeta: '2 a 3 horas · presencial o en remoto',
    workshopCta: 'Pedir el taller',
    howEyebrow: 'Cómo trabajo',
    howTitle: 'De la demo al piloto, *sin sorpresas*.',
    steps: [
      ['Demo de 15 minutos', 'Os enseño el servicio con documentos de ejemplo y me contáis vuestro caso.'],
      ['Propuesta con precio cerrado', 'Alcance, plazos y precio por escrito antes de empezar. Todos los pilotos caben en un contrato menor.'],
      ['Piloto acotado', 'Con vuestros documentos reales y durante un periodo corto. Al terminar, decidís si seguir.'],
    ],
    principles: [
      ['La secretaría valida siempre.', 'Ningún documento sale sin que lo revise una persona de vuestro equipo.'],
      ['Datos en la UE.', 'Se procesan en servidores de la Unión Europea, con contrato de encargado del tratamiento (art. 28 RGPD).'],
      ['Vuestros datos no entrenan modelos.', 'Se usan solo para vuestro servicio y se borran al terminar.'],
      ['Accesible por defecto.', 'Lo que entrego cumple la misma norma de accesibilidad que os ayudo a cumplir.'],
    ],
    demosEyebrow: 'Demos',
    demosTitle: 'Vedlo funcionar',
    demosText: 'Los vídeos de las demos estarán aquí muy pronto. Mientras tanto, os la enseño en directo en 15 minutos.',
    demosCta: 'Pedir demo →',
    dataEyebrow: 'Protección de datos',
    dataTitle: 'Una hoja para el expediente',
    dataText: 'Una página con qué datos se tratan, dónde, durante cuánto tiempo y con qué garantías, lista para adjuntar al expediente.',
    dataCta: 'Pedir la hoja de protección de datos →',
    whoEyebrow: 'Quién soy',
    whoText: 'Soy Victor Esteban, ingeniero de software en Valencia. Llevo más de 5 años construyendo y manteniendo sistemas en producción para empresas como Toyota, Inditex y Mercadona, y estoy certificado como Claude Certified Architect.',
    whoLink: 'Ver mi trayectoria completa →',
    closingTitle: '¿Lo vemos en *15 minutos*?',
    closingPlace: 'Valencia · en remoto o presencial',
    closingCta: 'Pedir una demo',
    demoSubject: 'Demo de 15 minutos',
    contactLead: 'Cuéntame qué os interesa y te escribo para buscar un hueco. Si lo prefieres, escríbeme directamente:',
    form: {
      name: 'Nombre y apellidos',
      org: 'Organismo',
      orgPlaceholder: 'Ayuntamiento de…',
      role: 'Cargo',
      email: 'Correo electrónico',
      phone: 'Teléfono',
      optional: 'opcional',
      interest: '¿Qué os interesa?',
      interests: [
        ['accesibilidad', 'Accesibilidad web'],
        ['actas', 'Actas de pleno con IA'],
        ['asistente', 'Asistente o anonimización'],
        ['taller', 'Taller de IA'],
        ['datos', 'Hoja de protección de datos'],
        ['otro', 'Otra cosa'],
      ],
      message: 'Mensaje',
      messagePlaceholder: 'Contadme vuestro caso, o cuándo os viene bien la demo.',
      consent: 'He leído la información sobre protección de datos y acepto que se usen mis datos para responder a esta solicitud.',
      privacyTitle: 'Protección de datos',
      privacy: [
        ['Responsable', 'Victor Esteban (hola@victoresteban.com).'],
        ['Finalidad', 'Responder a tu solicitud y, si os interesa, preparar una propuesta.'],
        ['Legitimación', 'Tu consentimiento.'],
        ['Destinatarios', 'Nadie más. El formulario se envía a través de Cloudflare y llega a mi correo (Google), que actúan como encargados del tratamiento.'],
        ['Conservación', 'Mientras dure la conversación y, como máximo, un año después si no hay contratación.'],
        ['Derechos', 'Acceso, rectificación, supresión, oposición, limitación y portabilidad, en hola@victoresteban.com. También puedes reclamar ante la Agencia Española de Protección de Datos (aepd.es).'],
      ],
      honeypot: 'No rellenes este campo',
      submit: 'Enviar solicitud',
    },
    thanksTitle: 'Solicitud enviada — Victor Esteban',
    thanksHeading: 'Gracias, he recibido tu *solicitud*.',
    thanksText: 'Te escribo al correo que me has indicado para buscar un hueco para la demo. Si es urgente, escríbeme a hola@victoresteban.com.',
    thanksBack: 'Volver a los servicios',
    backToTop: 'Volver arriba ↑',
  },

  va: {
    title: 'Accessibilitat web i IA per a ajuntaments — Victor Esteban',
    description: 'Accessibilitat web, actes de ple amb IA i assistents amb els documents del mateix ajuntament. Pilots acotats amb preu tancat, dades a la UE i sempre amb validació de secretaria.',
    skip: 'Ves al contingut',
    brandLabel: 'Victor Esteban, veure la trajectòria completa',
    headerRole: 'Serveis per a administracions públiques',
    sectionsLabel: 'Seccions',
    languageLabel: 'Idioma',
    navServices: 'Serveis',
    navHow: 'Com treballe',
    navDemo: 'Demanar demo',
    introLabel: 'Introducció',
    eyebrow: 'Per a ajuntaments i altres administracions públiques',
    headline: 'Accessibilitat web i *IA pràctica* per a ajuntaments.',
    lede: 'Vos ajude a complir la normativa d’accessibilitat i a estalviar hores de secretaria amb IA: actes de ple, respostes a partir dels vostres propis documents i anonimització per al portal de transparència. Pilots xicotets, amb preu tancat, i sempre amb una persona del vostre equip validant el resultat.',
    ctaDemo: 'Demaneu una demo de 15 minuts',
    ctaServices: 'Veure els serveis ↓',
    sheetTitle: 'Fitxa del servei',
    stamp: 'Contracte menor',
    sheet: [
      ['Contractació', 'Contracte menor, amb preu tancat abans de començar'],
      ['Format', 'Pilot acotat amb els vostres documents reals'],
      ['Revisió', 'Sempre vostra. No es publica res sense validar'],
      ['Dades', 'Tractades a la UE, amb contracte d’encàrrec (RGPD)'],
      ['Idiomes', 'Castellà i valencià'],
    ],
    servicesEyebrow: 'Serveis',
    servicesTitle: 'Tres problemes concrets, *resolts* amb pilots xicotets.',
    deliverables: 'Què rebeu',
    services: [
      {
        tile: 'flor',
        tag: 'Diagnòstic · correcció · manteniment',
        name: 'Accessibilitat web',
        audience: 'Lloc web municipal i seu electrònica',
        problem: 'El Reial decret 1112/2018 obliga que el lloc web i la seu electrònica siguen accessibles i que publiquen una declaració d’accessibilitat actualitzada. Molts no passen una revisió bàsica: contrast, formularis, navegació amb teclat o PDF sense etiquetar.',
        items: [
          'Diagnòstic segons la norma UNE-EN 301 549 (WCAG 2.1 AA), amb cada problema prioritzat.',
          'Correcció de les incidències, o instruccions concretes per al vostre proveïdor.',
          'Declaració d’accessibilitat redactada i preparada per a publicar.',
          'Manteniment anual opcional: revisions periòdiques i suport amb les reclamacions.',
        ],
      },
      {
        tile: 'estrella',
        tag: 'Pilot de 3 mesos',
        name: 'Actes de ple amb IA',
        audience: 'Secretaria',
        problem: 'Redactar l’acta d’un ple a partir de la gravació costa hores de secretaria: escoltar, transcriure, resumir cada intervenció i recollir els acords i les votacions.',
        items: [
          'Transcripció de la gravació, en castellà o en valencià, amb cada intervenció identificada.',
          'Esborrany de l’acta amb el format del vostre ajuntament: assistència, ordre del dia, intervencions, acords i votacions.',
          'La secretaria revisa, corregix i signa. L’eina només prepara l’esborrany.',
        ],
      },
      {
        tile: 'rombe',
        tag: 'Pilot acotat',
        name: 'Assistent amb els vostres documents',
        audience: 'Secretaria o atenció ciutadana',
        problem: 'Les mateixes preguntes arriben una vegada i una altra a secretaria o a atenció ciutadana, i la resposta està en una ordenança, un procediment o una resolució que cal buscar.',
        items: [
          'Un assistent per al personal o per a la ciutadania que respon a partir de les vostres ordenances, procediments i tràmits.',
          'Cada resposta cita el document d’on ix, per a poder comprovar-la.',
          'Avisa que és una IA, com exigix el Reglament europeu d’IA.',
          'El pilot se centra en una àrea o un tipus de consulta.',
        ],
        variant: {
          label: 'Variant xicoteta',
          name: 'Anonimització de documents.',
          text: 'Resolucions, contractes o actes preparats per al portal de transparència, amb les dades personals ocultes i una llista del que s’ha ocultat per a revisar-la abans de publicar.',
        },
      },
    ],
    workshopKicker: 'Per a començar',
    workshopTitle: 'Taller d’IA per a secretaria i intervenció',
    workshopText: 'Una sessió pràctica amb el vostre equip: què pot fer hui la IA amb documents municipals, què no convé fer-ne i com usar-la sense exposar dades personals. Sense compromís de contractar res més.',
    workshopMeta: 'De 2 a 3 hores · presencial o en remot',
    workshopCta: 'Demanar el taller',
    howEyebrow: 'Com treballe',
    howTitle: 'De la demo al pilot, *sense sorpreses*.',
    steps: [
      ['Demo de 15 minuts', 'Vos mostre el servei amb documents d’exemple i em conteu el vostre cas.'],
      ['Proposta amb preu tancat', 'Abast, terminis i preu per escrit abans de començar. Tots els pilots caben en un contracte menor.'],
      ['Pilot acotat', 'Amb els vostres documents reals i durant un període curt. En acabar, decidiu si continuar.'],
    ],
    principles: [
      ['La secretaria valida sempre.', 'Cap document ix sense que el revise una persona del vostre equip.'],
      ['Dades a la UE.', 'Es processen en servidors de la Unió Europea, amb contracte d’encarregat del tractament (art. 28 RGPD).'],
      ['Les vostres dades no entrenen models.', 'S’usen només per al vostre servei i s’esborren en acabar.'],
      ['Accessible per defecte.', 'El que entregue complix la mateixa norma d’accessibilitat que vos ajude a complir.'],
    ],
    demosEyebrow: 'Demos',
    demosTitle: 'Vegeu-lo funcionar',
    demosText: 'Els vídeos de les demos estaran ací molt prompte. Mentrestant, vos la mostre en directe en 15 minuts.',
    demosCta: 'Demanar demo →',
    dataEyebrow: 'Protecció de dades',
    dataTitle: 'Un full per a l’expedient',
    dataText: 'Una pàgina amb quines dades es tracten, on, durant quant de temps i amb quines garanties, preparada per a adjuntar a l’expedient.',
    dataCta: 'Demanar el full de protecció de dades →',
    whoEyebrow: 'Qui soc',
    whoText: 'Soc Victor Esteban, enginyer de programari a València. Fa més de 5 anys que construïsc i mantinc sistemes en producció per a empreses com Toyota, Inditex i Mercadona, i tinc la certificació Claude Certified Architect.',
    whoLink: 'Veure la meua trajectòria completa (en castellà) →',
    closingTitle: 'Ho veiem en *15 minuts*?',
    closingPlace: 'València · en remot o presencial',
    closingCta: 'Demanar una demo',
    demoSubject: 'Demo de 15 minuts',
    contactLead: 'Conteu-me què vos interessa i vos escric per a buscar un moment. Si ho preferiu, escriviu-me directament:',
    form: {
      name: 'Nom i cognoms',
      org: 'Organisme',
      orgPlaceholder: 'Ajuntament de…',
      role: 'Càrrec',
      email: 'Correu electrònic',
      phone: 'Telèfon',
      optional: 'opcional',
      interest: 'Què vos interessa?',
      interests: [
        ['accesibilidad', 'Accessibilitat web'],
        ['actas', 'Actes de ple amb IA'],
        ['asistente', 'Assistent o anonimització'],
        ['taller', 'Taller d’IA'],
        ['datos', 'Full de protecció de dades'],
        ['otro', 'Una altra cosa'],
      ],
      message: 'Missatge',
      messagePlaceholder: 'Conteu-me el vostre cas, o quan vos va bé la demo.',
      consent: 'He llegit la informació sobre protecció de dades i accepte que s’usen les meues dades per a respondre a esta sol·licitud.',
      privacyTitle: 'Protecció de dades',
      privacy: [
        ['Responsable', 'Victor Esteban (hola@victoresteban.com).'],
        ['Finalitat', 'Respondre a la vostra sol·licitud i, si vos interessa, preparar una proposta.'],
        ['Legitimació', 'El vostre consentiment.'],
        ['Destinataris', 'Ningú més. El formulari s’envia a través de Cloudflare i arriba al meu correu (Google), que actuen com a encarregats del tractament.'],
        ['Conservació', 'Mentre dure la conversa i, com a màxim, un any després si no hi ha contractació.'],
        ['Drets', 'Accés, rectificació, supressió, oposició, limitació i portabilitat, en hola@victoresteban.com. També podeu reclamar davant de l’Agència Espanyola de Protecció de Dades (aepd.es).'],
      ],
      honeypot: 'No ompliu este camp',
      submit: 'Enviar la sol·licitud',
    },
    thanksTitle: 'Sol·licitud enviada — Victor Esteban',
    thanksHeading: 'Gràcies, he rebut la vostra *sol·licitud*.',
    thanksText: 'Vos escric al correu que m’heu indicat per a buscar un moment per a la demo. Si és urgent, escriviu-me a hola@victoresteban.com.',
    thanksBack: 'Tornar als serveis',
    backToTop: 'Tornar amunt ↑',
  },

  en: {
    title: 'Web accessibility and AI for town councils — Victor Esteban',
    description: 'Web accessibility, AI-drafted council minutes and assistants built on the council’s own documents. Small fixed-price pilots, data processed in the EU, and your staff always validate the result.',
    skip: 'Skip to content',
    brandLabel: 'Victor Esteban, see full background',
    headerRole: 'Services for public administrations',
    sectionsLabel: 'Sections',
    languageLabel: 'Language',
    navServices: 'Services',
    navHow: 'How I work',
    navDemo: 'Book a demo',
    introLabel: 'Introduction',
    eyebrow: 'For town councils and other public bodies',
    headline: 'Web accessibility and *practical AI* for town councils.',
    lede: 'I help councils meet accessibility law and save hours of clerk’s office work with AI: minutes of council meetings, answers drawn from your own documents, and anonymisation for the transparency portal. Small pilots at a fixed price, always with someone on your team validating the result.',
    ctaDemo: 'Book a 15-minute demo',
    ctaServices: 'See the services ↓',
    sheetTitle: 'Service sheet',
    stamp: 'Minor contract',
    sheet: [
      ['Procurement', 'Minor contract (contrato menor), fixed price agreed up front'],
      ['Format', 'A scoped pilot on your real documents'],
      ['Review', 'Always yours. Nothing is published unvalidated'],
      ['Data', 'Processed in the EU, under a GDPR processing agreement'],
      ['Languages', 'Spanish and Valencian'],
    ],
    servicesEyebrow: 'Services',
    servicesTitle: 'Three concrete problems, *solved* with small pilots.',
    deliverables: 'What you get',
    services: [
      {
        tile: 'flor',
        tag: 'Audit · fixes · maintenance',
        name: 'Web accessibility',
        audience: 'Council website and e-office (sede electrónica)',
        problem: 'Royal Decree 1112/2018 requires the website and e-office to be accessible and to publish an up-to-date accessibility statement. Many fail a basic review: contrast, forms, keyboard navigation or untagged PDFs.',
        items: [
          'An audit against EN 301 549 (WCAG 2.1 AA), with every issue prioritised.',
          'Fixes for the issues found, or precise instructions for your web provider.',
          'An accessibility statement, written and ready to publish.',
          'Optional yearly maintenance: periodic reviews and help with complaints.',
        ],
      },
      {
        tile: 'estrella',
        tag: '3-month pilot',
        name: 'AI-drafted council minutes',
        audience: 'Clerk’s office (secretaría)',
        problem: 'Writing up the minutes of a council meeting from the recording takes the clerk’s office hours: listening, transcribing, summarising each speaker and recording the resolutions and votes.',
        items: [
          'A transcript of the recording, in Spanish or Valencian, with each speaker identified.',
          'Draft minutes in your council’s format: attendance, agenda, speeches, resolutions and votes.',
          'The clerk reviews, corrects and signs. The tool only prepares the draft.',
        ],
      },
      {
        tile: 'rombe',
        tag: 'Scoped pilot',
        name: 'An assistant on your own documents',
        audience: 'Clerk’s office or citizen services',
        problem: 'The same questions reach the clerk’s office or citizen services again and again, and the answer sits in a bylaw, a procedure or a resolution that someone has to look up.',
        items: [
          'An assistant for staff or for the public that answers from your bylaws, procedures and services.',
          'Every answer cites the document it comes from, so it can be checked.',
          'It says it is an AI, as the EU AI Act requires.',
          'The pilot focuses on one area or one type of question.',
        ],
        variant: {
          label: 'Smaller variant',
          name: 'Document anonymisation.',
          text: 'Resolutions, contracts or minutes ready for the transparency portal, with personal data removed and a list of what was removed to review before publishing.',
        },
      },
    ],
    workshopKicker: 'To start',
    workshopTitle: 'AI workshop for the clerk’s and comptroller’s offices',
    workshopText: 'A hands-on session with your team: what AI can do with council documents today, what it should not be used for, and how to use it without exposing personal data. No commitment to buy anything else.',
    workshopMeta: '2 to 3 hours · on site or remote',
    workshopCta: 'Ask for the workshop',
    howEyebrow: 'How I work',
    howTitle: 'From demo to pilot, *no surprises*.',
    steps: [
      ['15-minute demo', 'I show you the service on sample documents and you tell me about your case.'],
      ['Fixed-price proposal', 'Scope, timeline and price in writing before we start. Every pilot fits within a minor contract.'],
      ['Scoped pilot', 'On your real documents, for a short period. At the end, you decide whether to continue.'],
    ],
    principles: [
      ['The clerk always validates.', 'No document goes out without review by someone on your team.'],
      ['Data stays in the EU.', 'Processed on servers in the European Union, under a data processing agreement (GDPR art. 28).'],
      ['Your data trains no models.', 'It is used only for your service and deleted at the end.'],
      ['Accessible by default.', 'What I deliver meets the same accessibility standard I help you meet.'],
    ],
    demosEyebrow: 'Demos',
    demosTitle: 'See it working',
    demosText: 'Demo videos will be here very soon. Until then, I can show you one live in 15 minutes.',
    demosCta: 'Book a demo →',
    dataEyebrow: 'Data protection',
    dataTitle: 'A sheet for the procurement file',
    dataText: 'One page on what data is processed, where, for how long and with what safeguards, ready to attach to the file.',
    dataCta: 'Ask for the data protection sheet →',
    whoEyebrow: 'About me',
    whoText: 'I’m Victor Esteban, a software engineer in Valencia. I’ve spent 5+ years building and running production systems for companies such as Toyota, Inditex and Mercadona, and I’m a Claude Certified Architect.',
    whoLink: 'See my full background →',
    closingTitle: 'Shall we talk for *15 minutes*?',
    closingPlace: 'Valencia · remote or on site',
    closingCta: 'Book a demo',
    demoSubject: '15-minute demo',
    contactLead: 'Tell me what you are interested in and I will write back to find a time. If you prefer, email me directly:',
    form: {
      name: 'Full name',
      org: 'Organisation',
      orgPlaceholder: 'Town council of…',
      role: 'Position',
      email: 'Email',
      phone: 'Phone',
      optional: 'optional',
      interest: 'What are you interested in?',
      interests: [
        ['accesibilidad', 'Web accessibility'],
        ['actas', 'AI-drafted council minutes'],
        ['asistente', 'Assistant or anonymisation'],
        ['taller', 'AI workshop'],
        ['datos', 'Data protection sheet'],
        ['otro', 'Something else'],
      ],
      message: 'Message',
      messagePlaceholder: 'Tell me about your case, or when suits you for the demo.',
      consent: 'I have read the data protection information and agree to my data being used to answer this request.',
      privacyTitle: 'Data protection',
      privacy: [
        ['Controller', 'Victor Esteban (hola@victoresteban.com).'],
        ['Purpose', 'To answer your request and, if you are interested, prepare a proposal.'],
        ['Legal basis', 'Your consent.'],
        ['Recipients', 'Nobody else. The form is sent through Cloudflare and reaches my mailbox (Google), both acting as processors.'],
        ['Retention', 'For as long as the conversation lasts and at most one year after it if nothing is contracted.'],
        ['Your rights', 'Access, rectification, erasure, objection, restriction and portability, at hola@victoresteban.com. You can also complain to the Spanish Data Protection Agency (aepd.es).'],
      ],
      honeypot: 'Leave this field empty',
      submit: 'Send request',
    },
    thanksTitle: 'Request sent — Victor Esteban',
    thanksHeading: 'Thank you, I have your *request*.',
    thanksText: 'I will write to the email you gave me to find a time for the demo. If it is urgent, email me at hola@victoresteban.com.',
    thanksBack: 'Back to the services',
    backToTop: 'Back to top ↑',
  },
};
